### PR TITLE
Hypercert sdk

### PR DESCRIPTION
**Pull request by carlbarrdahl**
Update to use new Hypercerts SDK.

Some issues:
- `mintHypercertToken` not using the correct provider from Wagmi
  - `ethers.getDefaultProvider` returns a FallbackProvider with network set to `homestead`
  - See https://github.com/carlbarrdahl/gratitude.party/pull/1#issuecomment-1434109741
- Functions from `/minting.ts` are not being exported, for example `mintHypercertToken`
  - Workaround to import `@hypercerts-org/hypercerts-sdk/lib/minting`
 - Fixed in [b68b9d6](https://github.com/carlbarrdahl/gratitude.party/pull/1/commits/b68b9d6d214b47a866edf61123d710cc0a539f3c)! ~~`claimById` not finding the minted token (different contract addresses?)~~
   - https://github.com/carlbarrdahl/gratitude.party/blob/efad03226d6fa7e049e5fbdf42494b59afa66ab3/src/hooks/useHypercert.ts#L6-L12
- Fixed in 0044ced ~~NFT.Storage token is configured as `process.env.NFT_STORAGE_TOKEN`~~
  - How to set this in a Next.js app that expects `NEXT_PUBLIC_` prefix?
  - https://github.com/hypercerts-org/hypercerts/blob/2be7d9c0bcc490f22c434f989e37dde58baecb84/sdk/src/operator/index.ts#L7
  - https://github.com/carlbarrdahl/gratitude.party/blob/efad03226d6fa7e049e5fbdf42494b59afa66ab3/src/hooks/useMint.ts#L40-L41

### CODE REVIEW

**Comment by bitbeckers** [comment]
Hi checking in via Cristina.

_"NFT.Storage token is configured as process.env.NFT_STORAGE_TOKEN 
How to set this in a Next.js app that expects NEXT_PUBLIC_ prefix?"_
    
```js
module.exports = {
  env: {
    NFT_STORAGE_TOKEN: process.env.NEXT_PUBLIC_NFT_STORAGE_TOKEN,
  },
}
```

Ref: https://nextjs.org/docs/api-reference/next.config.js/environment-variables

**Comment by bitbeckers** [comment]
_Functions from /minting.ts are not being exported, for example mintHypercertToken
Workaround to import @hypercerts-org/hypercerts-sdk/lib/minting_

Created a bug report: https://github.com/hypercerts-org/hypercerts/issues/303

Good if the workaround works. Alternative you can use the exports ABIs to create a contract instance with your web3-lib of choice.

**Comment by carlbarrdahl** [comment]
> Hi checking in via Cristina.
> 
> _"NFT.Storage token is configured as process.env.NFT_STORAGE_TOKEN How to set this in a Next.js app that expects NEXT_PUBLIC_ prefix?"_
> 
> Set up `next.config.js` with:
> 
> ```js
> module.exports = {
>   env: {
>     NFT_STORAGE_TOKEN: process.env.NEXT_PUBLIC_NFT_STORAGE_TOKEN,
>   },
> }
> ```
> 
> Ref: https://nextjs.org/docs/api-reference/next.config.js/environment-variables

Thank you @bitbeckers! This works! 
Could be a good idea to provide a bare minimal example of integrating Hypercerts SDK in a Next.js project.

**Comment by carlbarrdahl** [comment]
> _Functions from /minting.ts are not being exported, for example mintHypercertToken Workaround to import @hypercerts-org/hypercerts-sdk/lib/minting_
> 
> Created a bug report: [hypercerts-org/hypercerts#303](https://github.com/hypercerts-org/hypercerts/issues/303)
> 
> Good if the workaround works. Alternative you can use the exports ABIs to create a contract instance with your web3-lib of choice.

Now that the NFT Storage works I get an error when calling the actual contract.

```
Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.7.0)
```

This is because: `ethers.getDefaultProvider()` returns a FallbackProvider:

https://github.com/hypercerts-org/hypercerts/blob/f29438afcb75e9acab20074aa31c3093e6318505/sdk/src/utils/provider.ts#L3-L4

It would be great if it was possible to call `mintHypercertToken` with a signer in the parameters:

```tsx
export const useMintHypercert = (
  onSuccess: (data?: ContractTransaction) => void
) => {
  const { data: signer } = useSigner();
  return useMutation(async (claimData: HypercertMetadata) =>
    mintHypercertToken([claimData, 1, transferRestrictions.AllowAll], signer).then(
      onSuccess
    )
  );
};
```

Any other way of resolving this?

**Pull request merged**
